//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBan
    {
        public int ID { get; set; }
        public string SoHDB { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public string MaKhach { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual ChiTietHDB ChiTietHDB { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
