//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.ChiTietHDB = new HashSet<ChiTietHDB>();
            this.ChiTietHDN = new HashSet<ChiTietHDN>();
        }
    
        public int ID { get; set; }
        public string MaGiayDep { get; set; }
        public string TenGiayDep { get; set; }
        public string MaLoai { get; set; }
        public string MaCo { get; set; }
        public string MaChatLieu { get; set; }
        public string MaMau { get; set; }
        public string MaDoiTuong { get; set; }
        public string MaMua { get; set; }
        public string MaNuocSX { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string Anh { get; set; }
        public Nullable<decimal> DonGiaNhap { get; set; }
        public Nullable<decimal> DonGiaBan { get; set; }
    
        public virtual ChatLieu ChatLieu { get; set; }
        public virtual ICollection<ChiTietHDB> ChiTietHDB { get; set; }
        public virtual ICollection<ChiTietHDN> ChiTietHDN { get; set; }
        public virtual DoiTuong DoiTuong { get; set; }
        public virtual KichCo KichCo { get; set; }
        public virtual Mau Mau { get; set; }
        public virtual Mua Mua { get; set; }
        public virtual NuocSanXuat NuocSanXuat { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
