//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Core.Domain
{
    using System;
    using System.Collections.Generic;

    public partial class ChiTietHDB: BaseEntity
    {
        //public int ID { get; set; }
        public string MaGiayDep { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string GiamGia { get; set; }
        public string ThanhTien { get; set; }
        public string SoHDB { get; set; }
    
        public virtual HoaDonBan HoaDonBan { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
