//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Core.Domain
{
    using System;
    using System.Collections.Generic;

    public partial class HoaDonNhap: BaseEntity
    {
        //public int ID { get; set; }
        public string soHDN { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string MaNCC { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual ChiTietHDN ChiTietHDN { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
